#
# Makefile for the drm device driver.  This driver provides support for the
# Direct Rendering Infrastructure (DRI) in XFree86 4.1.0 and higher.

axi_kutu_hdmi-y := axi_kutu_hdmi_encoder.o axi_kutu_hdmi_crtc.o axi_kutu_hdmi_drv.o

obj-$(CONFIG_DRM_AXI_KUTU_HDMI) += axi_kutu_hdmi.o
