#
# Makefile for the drm device driver.  This driver provides support for the
# Direct Rendering Infrastructure (DRI) in XFree86 4.1.0 and higher.

kutu_hdmi-y := kutu_hdmi_encoder.o kutu_hdmi_crtc.o kutu_hdmi_drv.o

obj-$(CONFIG_DRM_KUTU_HDMI) += kutu_hdmi.o
